import { FaLine, FaWhatsapp } from 'react-icons/fa';
import { RxEyeNone } from 'react-icons/rx';

export const PENDAFTARAN_STAFF_PAGES = [
  {
    id: 1,
    name: 'Informasi Pribadi',
    pertanyaan: ['nama', 'email', 'nrp', 'fakultas_id', 'asal_departemen'],
  },
  {
    id: 2,
    name: 'Pertanyaan Umum',
    pertanyaan: [
      'ketahui',
      'motivasi',
      'inovasi',
      'pilihan_pertama',
      'pilihan_kedua',
      'pilihan_ketiga',
      'prioritas',
    ],
  },
  { id: 3, name: 'Pertanyaan Divisi 1' },
  { id: 4, name: 'Pertanyaan Divisi 2' },
  { id: 5, name: 'Pertanyaan Divisi 3' },
  { id: 6, name: 'Dokumen Pendukung' },
];

export const PENDAFTARAN_STAFF_DIVISIONS = [
  { id: 2, name: 'Event' },
  { id: 3, name: 'Sponsorship' },
  { id: 4, name: 'Fundraising' },
  { id: 5, name: 'Design Creative' },
  { id: 6, name: 'Documentation' },
  { id: 7, name: 'Dekorasi' },
  { id: 8, name: 'Social Media Marketing' },
  { id: 9, name: 'Content Creator' },
  { id: 10, name: 'Public Relation' },
  { id: 11, name: 'Consumption' },
  { id: 12, name: 'Security & License' },
  { id: 13, name: 'Equipment' },
  { id: 14, name: 'Kestari' },
  { id: 15, name: 'Web Development' },
  { id: 16, name: 'Medical' },
] as const;

export const DIVISIONS = [
  {
    id: 0,
    name: 'No Division',
    iconType: RxEyeNone,
    contact: 'no contact',
    href: '/',
  },
  {
    id: 1,
    name: 'BPH',
    iconType: RxEyeNone,
    contact: 'no contact',
    href: '/',
  },
  {
    id: 2,
    name: 'Event',
    iconType: FaLine,
    contact: 'keisyafatikaa (Keisya)',
    href: '/',
  },
  {
    id: 3,
    name: 'Sponsorship',
    iconType: FaWhatsapp,
    contact: '082331725303 (Fakhri)',
    href: 'https://wa.me/6282331725303',
  },
  {
    id: 4,
    name: 'Fundraising',
    iconType: FaWhatsapp,
    contact: '082331725303 (Fakhri)',
    href: 'https://wa.me/6282331725303',
  },
  {
    id: 5,
    name: 'Design Creative',
    iconType: FaWhatsapp,
    contact: '082211158985 (Arka)',
    href: 'https://wa.me/6282211158985',
  },
  {
    id: 6,
    name: 'Documentation',
    iconType: FaWhatsapp,
    contact: '082166267802 (Theo)',
    href: 'https://wa.me/6282166267802',
  },
  {
    id: 7,
    name: 'Dekorasi',
    iconType: FaWhatsapp,
    contact: '082297075207 (Sophie)',
    href: 'https://wa.me/6282297075207',
  },
  {
    id: 8,
    name: 'Social Media Marketing',
    iconType: FaLine,
    contact: 'ardeliasyanda (Syanda)',
    href: '/',
  },
  {
    id: 9,
    name: 'Content Creator',
    iconType: FaLine,
    contact: 'wendi_maulana (Wendi)',
    href: '/',
  },
  {
    id: 10,
    name: 'Public Relation',
    iconType: FaLine,
    contact: 'mfazms (Fazle)',
    href: '/',
  },
  {
    id: 11,
    name: 'Consumption',
    iconType: FaWhatsapp,
    contact: '085797650755 (Fahmi)',
    href: 'https://wa.me/6285797650755',
  },
  {
    id: 12,
    name: 'Security & License',
    iconType: FaWhatsapp,
    contact: '089655098138 (Aji)',
    href: 'https://wa.me/6289655098138',
  },
  {
    id: 13,
    name: 'Equipment',
    iconType: FaLine,
    contact: 'marcellohugo__ (Marco)',
    href: '/',
  },
  {
    id: 14,
    name: 'Kestari',
    iconType: FaWhatsapp,
    contact: '081247957157 (Amai)',
    href: 'https://wa.me/6281247957157',
  },
  {
    id: 15,
    name: 'Web Development',
    iconType: FaWhatsapp,
    contact: '087747447576 (Ainun)',
    href: 'https://wa.me/6287747447576',
  },
  {
    id: 16,
    name: 'Medical',
    iconType: FaWhatsapp,
    contact: '082143158181 (Ghazan)',
    href: 'https://wa.me/6282143158181',
  },
] as const;
